name: yumquick
description: "A new Flutter food delivery application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  get: ^4.7.2
  gap: ^3.0.1
  responsive_sizer: ^3.3.1
  flutter_svg: ^2.2.1
  dropdown_button2: ^2.3.9
  hive: ^2.2.3
  flutter_rating_stars: ^1.1.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.3
  form_builder_validators: ^11.2.0
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_gen_runner: ^5.12.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

# âŒ Local fonts REMOVED to avoid build failure
# Use GoogleFonts.poppins() instead

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: false
    lottie: true

  assets:
    enabled: true

  fonts:
    enabled: false
